### ISSUE TITLE
SMS Gateway with https link

### ISSUE THREAD

**Issue by jimeshm** [tlenss/zabbix-sms-client#3]
Hi,

How can set conf.php for below SMS Gateway.

https://api.infobip.com/sms/1/text/query?username=user1&password=pass1&to=911234423432&text=%%%TEXT%%%&from=TSTSMS

Thanks,
Jimesh Makwana

**Comment by tlenss** [comment]
I have added a pull request for the infobip api. You can give that a try

https://github.com/tlenss/zabbix-sms-client/pull/4

**Comment by tlenss** [comment]
Merged
